module

public import Lean.Elab.Frontend
public import AFTK.Server
public import Lake.Build.Infos
public import Lake.Build.Job.Monad
public import Lake.Build.Library
public import Lake.Build.Run
public import Lake.Load.Workspace

public section

namespace AFTK.TechDebt

open Lean
open Lean.Elab

/-- A category of technical debt recognized by AFTK. -/
inductive Kind where
  /-- A command that overrides Lean's heartbeat limit. -/
  | maxHeartbeats
  /-- A command that overrides Lean's recursion-depth limit. -/
  | maxRecDepth
  /-- A command that disables Lean's built-in resource limits. -/
  | unlockLimits
  /-- A Lean backwards-compatibility option override. -/
  | backwardOption
  /-- A disabled flexible linter. -/
  | linterFlexible
  /-- A disabled overlapping-instances linter. -/
  | linterOverlappingInstances
  /-- A disabled autogenerated-auxiliary-lemma linter. -/
  | linterAuxLemma
  /-- A disabled deprecation linter. -/
  | linterDeprecated
  /-- A disabled simplifier variable-head warning. -/
  | simpVarHead
  /-- A development-only debug, pretty-printing, profiler, or trace option. -/
  | developmentOption
  /-- An override of the configured long-file limit. -/
  | longFile
  /-- An invocation of Core Lean's `erw` tactic. -/
  | erw
  /-- A `simp` invocation that enables instance unfolding. -/
  | simpInstances
  /-- A `dsimp` invocation that enables instance unfolding. -/
  | dsimpInstances
  /-- A Mathlib adaptation note. -/
  | adaptationNote
  /-- A disabled `simpNF` lint. -/
  | simpNF
  /-- An exposed public section. -/
  | exposePublic
  /-- An opening of the backwards-compatible `Fin.CommRing` namespace. -/
  | finCommRing
  /-- An opening of the backwards-compatible `Fin.NatCast` namespace. -/
  | finNatCast
  /-- A `sorry` or `admit` placeholder. -/
  | sorry
  /-- A deprecated declaration or module. -/
  | deprecated
  /-- An axiom declaration. -/
  | axiom
  deriving Inhabited, BEq

namespace Kind

/-- Stable machine-readable name for a finding category. -/
def name : Kind → String
  | .maxHeartbeats => "maxHeartbeats"
  | .maxRecDepth => "maxRecDepth"
  | .unlockLimits => "unlockLimits"
  | .backwardOption => "backwardOption"
  | .linterFlexible => "linterFlexible"
  | .linterOverlappingInstances => "linterOverlappingInstances"
  | .linterAuxLemma => "linterAuxLemma"
  | .linterDeprecated => "linterDeprecated"
  | .simpVarHead => "simpVarHead"
  | .developmentOption => "developmentOption"
  | .longFile => "longFile"
  | .erw => "erw"
  | .simpInstances => "simpInstances"
  | .dsimpInstances => "dsimpInstances"
  | .adaptationNote => "adaptationNote"
  | .simpNF => "simpNF"
  | .exposePublic => "exposePublic"
  | .finCommRing => "finCommRing"
  | .finNatCast => "finNatCast"
  | .sorry => "sorry"
  | .deprecated => "deprecated"
  | .axiom => "axiom"

/-- Human-readable description of a finding category. -/
def description : Kind → String
  | .maxHeartbeats => "heartbeat limit override"
  | .maxRecDepth => "recursion-depth limit override"
  | .unlockLimits => "`unlock_limits` command"
  | .backwardOption => "Lean backwards-compatibility option override"
  | .linterFlexible => "disabled `linter.flexible` check"
  | .linterOverlappingInstances => "disabled `linter.overlappingInstances` check"
  | .linterAuxLemma => "disabled `linter.auxLemma` check"
  | .linterDeprecated => "disabled deprecation lint"
  | .simpVarHead => "disabled simplifier variable-head warning"
  | .developmentOption => "development-only option setting"
  | .longFile => "long-file limit override"
  | .erw => "Core Lean `erw` tactic invocation"
  | .simpInstances => "`simp +instances` invocation"
  | .dsimpInstances => "`dsimp +instances` invocation"
  | .adaptationNote => "Mathlib `#adaptation_note`"
  | .simpNF => "disabled `simpNF` lint"
  | .exposePublic => "`@[expose] public section`"
  | .finCommRing => "backwards-compatible `Fin.CommRing` namespace opening"
  | .finNatCast => "backwards-compatible `Fin.NatCast` namespace opening"
  | .sorry => "unfinished proof or value placeholder"
  | .deprecated => "deprecated declaration or module"
  | .axiom => "axiom declaration"

/-- Every technical-debt marker understood by AFTK, in CLI display order. -/
def all : Array Kind := #[
  .maxHeartbeats, .maxRecDepth, .unlockLimits, .backwardOption,
  .linterFlexible, .linterOverlappingInstances, .linterAuxLemma, .linterDeprecated,
  .simpVarHead, .developmentOption, .longFile, .erw, .simpInstances, .dsimpInstances,
  .adaptationNote, .simpNF, .exposePublic, .finCommRing, .finNatCast, .sorry, .deprecated, .axiom]

/-- Parse a stable marker name accepted by `--markers`. -/
def ofString? (value : String) : Option Kind :=
  all.find? fun kind => kind.name == value

/-- Marker names and descriptions for CLI help. -/
def help : String :=
  String.intercalate "\n" <| all.toList.map fun kind => s!"  {kind.name}: {kind.description}."

end Kind

/-- One technical-debt occurrence in a source module. Positions are 1-based. -/
structure Finding where
  moduleName : Name
  file : String
  kind : Kind
  start : Position
  stop : Position
  deriving Inhabited

/-- The configured scope of a technical-debt scan. -/
inductive Scope where
  /-- Scan one Lean module. -/
  | module (moduleName : Name)
  /-- Scan every module in one configured Lake library. -/
  | library (libraryName : Name)
  /-- Scan every Lean target in a Lake package; `none` selects the root package. -/
  | package (packageName? : Option Name)
  deriving Inhabited

/-- Parsed `tech-debt` command arguments. -/
structure Config where
  scope : Scope
  markers : Array Kind
  jsonl : Bool := false
  deriving Inhabited

/-- Help text for the `tech-debt` command. -/
def cliHelp : String :=
"Find technical debt in Lean modules, libraries, and packages using elaborator info trees.

Usage:
  lake exe aftk tech-debt [options]
  lake exe aftk tech-debt [options] module <module>
  lake exe aftk tech-debt [options] library <library>
  lake exe aftk tech-debt [options] package [<package>]
  lake exe aftk tech-debt [options] <module>

Scopes:
  (no scope)                Scan the root Lake package.
  module <module>           Scan one Lean module.
  library <library>         Scan modules enumerated by the Lake library's `modules` facet.
  package [<package>]       Scan all configured Lean libraries and executables in a package.
  <module>                  Compatibility shorthand for `module <module>`.

Options:
  --markers <list>   Required comma-separated marker names. May be repeated.
  --all-markers      Select every supported marker.
  --jsonl            Print one JSON object per finding instead of tab-separated rows.
  -h, --help         Show this help.

Markers:
" ++ Kind.help ++ "

Output:
  By default: <file>:<line>:<column>\t<kind>\t<description>.
  Positions are 1-based."

/-- Interpret positional arguments as a scan scope. -/
def parseScope (positionals : Array String) : Except String Scope := do
  match positionals.toList with
  | [] => return .package none
  | ["package"] => return .package none
  | ["package", packageName] => return .package (some packageName.toName)
  | ["module", moduleName] => return .module moduleName.toName
  | ["library", libraryName] => return .library libraryName.toName
  | [moduleName] => return .module moduleName.toName
  | "module" :: _ => throw "module scope expects exactly <module>"
  | "library" :: _ => throw "library scope expects exactly <library>"
  | "package" :: _ => throw "package scope accepts at most one <package>"
  | _ => throw "expected module <module>, library <library>, or package [<package>]"

/-- Deduplicate marker selections while preserving their command-line order. -/
def normalizeMarkers (markers : Array Kind) : Array Kind := Id.run do
  let mut result := #[]
  for marker in markers do
    unless result.contains marker do
      result := result.push marker
  return result

/-- Parse one comma-separated `--markers` value. -/
def parseMarkers (value : String) : Except String (Array Kind) := do
  let mut markers := #[]
  for rawMarker in value.splitOn "," do
    let markerName := rawMarker.trimAscii.toString
    if markerName.isEmpty then
      throw "marker names must not be empty"
    let some marker := Kind.ofString? markerName
      | throw s!"unknown technical-debt marker `{markerName}`"
    markers := markers.push marker
  return normalizeMarkers markers

/-- Parse `tech-debt` command arguments. `none` means help was requested. -/
def parseArgs (args : List String) : Except String (Option Config) := do
  let rec go (args : List String) (jsonl : Bool) (markers? : Option (Array Kind))
      (positionals : Array String) : Except String (Option Config) := do
    match args with
    | [] =>
        let some markers := markers?
          | throw "missing marker selection: use `--markers <list>` or `--all-markers`"
        return some { scope := ← parseScope positionals, markers := normalizeMarkers markers, jsonl }
    | "--help" :: _ | "-h" :: _ => return none
    | "--jsonl" :: rest => go rest true markers? positionals
    | "--all-markers" :: rest => go rest jsonl (some Kind.all) positionals
    | "--markers" :: value :: rest =>
        let selected ← parseMarkers value
        go rest jsonl (some (markers?.getD #[] ++ selected)) positionals
    | "--markers" :: [] => throw "missing value after `--markers`"
    | arg :: rest =>
        if arg.startsWith "--markers=" then
          let selected ← parseMarkers (arg.drop "--markers=".length).toString
          go rest jsonl (some (markers?.getD #[] ++ selected)) positionals
        else if arg.startsWith "-" then
          throw s!"unknown option `{arg}`"
        else
          go rest jsonl markers? (positionals.push arg)
  go args false none #[]

/-- Load the Lake workspace rooted at the current project. -/
def loadProjectWorkspace : IO Lake.Workspace := do
  let root ← Server.findProjectRoot
  let (elan?, lean?, lake?) ← Lake.findInstall?
  let some lean := lean?
    | throw <| IO.userError "could not locate the Lean installation"
  let lake := lake?.getD (Lake.LakeInstall.ofLean lean)
  let lakeEnv ← EIO.toIO (.userError ·) <| Lake.Env.compute lake lean elan?
  let workspace? ← (Lake.loadWorkspace {
    lakeEnv
    wsDir := root
    updateToolchain := false
  }).toBaseIO { outLv := .warning }
  let some workspace := workspace?
    | throw <| IO.userError s!"failed to load Lake workspace at `{root}`"
  return workspace

/-- Fetch the modules belonging to configured Lake libraries through their `modules` facets. -/
def libraryModules (workspace : Lake.Workspace) (libraries : Array Lake.LeanLib) : IO (Array Name) :=
  workspace.runFetchM (cfg := { verbosity := .quiet }) do
    let mut moduleNames := #[]
    for library in libraries do
      let modules ← (← library.modules.fetch).await
      moduleNames := moduleNames ++ modules.map (·.name)
    return moduleNames

/-- Deduplicate and sort module names for deterministic package scans. -/
def normalizeModuleNames (moduleNames : Array Name) : Array Name := Id.run do
  let mut seen : NameHashSet := {}
  let mut result := #[]
  for moduleName in moduleNames do
    unless seen.contains moduleName do
      seen := seen.insert moduleName
      result := result.push moduleName
  return result.qsort fun a b => toString a < toString b

/-- Resolve a CLI scan scope to the modules configured in the current Lake workspace. -/
def modulesForScope (workspace : Lake.Workspace) (scope : Scope) : IO (Array Name) := do
  match scope with
  | .module moduleName =>
      return #[moduleName]
  | .library libraryName =>
      let some library := workspace.findLeanLib? libraryName
        | throw <| IO.userError s!"could not find Lean library `{libraryName}` in the Lake workspace"
      return normalizeModuleNames (← libraryModules workspace #[library])
  | .package packageName? =>
      let package ← match packageName? with
        | none => pure workspace.root
        | some packageName =>
            let some package := workspace.findPackageByName? packageName
              | throw <| IO.userError s!"could not find package `{packageName}` in the Lake workspace"
            pure package
      let libraryModuleNames ← libraryModules workspace package.leanLibs
      let executableModuleNames := package.leanExes.map (·.root.name)
      return normalizeModuleNames (libraryModuleNames ++ executableModuleNames)

/-- Resolve a module's Lean source file using the current Lake project's source search path. -/
def resolveModuleSource (moduleName : Name) : IO System.FilePath := do
  let root ← Server.findProjectRoot
  let searchPath ← Server.projectSrcSearchPath root
  match ← searchPath.findModuleWithExt "lean" moduleName with
  | some path => IO.FS.realPath path
  | none => throw <| IO.userError s!"could not find source for module `{moduleName}` in the project source search path"

/-- Ensure the consuming Lake project's compiled-module paths are available to the elaborator. -/
def addProjectLeanSearchPath : IO Unit := do
  let root ← Server.findProjectRoot
  try
    let output ← IO.Process.output {
      cmd := "lake"
      args := #["env", "printenv", "LEAN_PATH"]
      cwd := some root
    }
    if output.exitCode == 0 then
      let raw := output.stdout.trimAscii.toString
      if !raw.isEmpty then
        let projectPath := System.SearchPath.parse raw
        let currentPath ← Lean.searchPathRef.get
        Lean.searchPathRef.set (projectPath ++ currentPath)
  catch _ =>
    pure ()

/-- Print elaboration errors and reject a module whose info trees are incomplete. -/
def ensureNoErrors (moduleName : Name) (messages : MessageLog) : IO Unit := do
  if messages.hasErrors then
    for message in messages.toList do
      if message.severity == .error then
        IO.eprintln (← message.toString)
    throw <| IO.userError s!"failed to elaborate module `{moduleName}`"

/-- Return the options Lake uses to build a configured module. -/
def moduleLeanOptions (workspace : Lake.Workspace) (moduleName : Name) : LeanOptions :=
  (workspace.findTargetModule? moduleName).map (·.leanOptions) |>.getD {}

/-- Elaborate a source module with the given Lake options and return its completed info trees. -/
def moduleInfoTreesWithOptions (moduleName : Name) (path : System.FilePath)
    (leanOptions : LeanOptions) :
    IO (FileMap × PersistentArray InfoTree) := do
  let input ← IO.FS.readFile path
  let inputCtx := Parser.mkInputContext input path.toString
  let (header, parserState, parseMessages) ← Parser.parseHeader inputCtx
  ensureNoErrors moduleName parseMessages
  unsafe Lean.enableInitializersExecution
  let options := leanOptions.toOptions
  let (env, headerMessages) ← Elab.processHeader header options parseMessages inputCtx
    (leakEnv := true) (mainModule := moduleName)
  ensureNoErrors moduleName headerMessages
  let options ← Lean.Language.Lean.reparseOptions options
  let commandState := Elab.Command.mkState env headerMessages options
  let state ← Elab.IO.processCommands inputCtx parserState commandState
  ensureNoErrors moduleName state.commandState.messages
  let infoState := state.commandState.infoState.substituteLazy.get
  return (inputCtx.fileMap, infoState.trees)

/-- Elaborate a source module with its configured Lake options and return its completed info trees. -/
def moduleInfoTrees (moduleName : Name) (path : System.FilePath) :
    IO (FileMap × PersistentArray InfoTree) := do
  let workspace ← loadProjectWorkspace
  moduleInfoTreesWithOptions moduleName path (moduleLeanOptions workspace moduleName)

/-- True when a syntax tree contains an atom with the given source spelling. -/
partial def syntaxContainsAtom (stx : Syntax) (value : String) : Bool :=
  match stx with
  | .atom _ atom => atom == value
  | .node _ _ args => args.any (syntaxContainsAtom · value)
  | _ => false

/-- True when a syntax tree contains an identifier with the given unscoped name. -/
partial def syntaxContainsIdent (stx : Syntax) (value : Name) : Bool :=
  if stx.isIdent && stx.getId.eraseMacroScopes == value then
    true
  else
    stx.getArgs.any (syntaxContainsIdent · value)

/-- True when syntax contains a name either as an identifier or as a parser keyword. -/
def syntaxContainsNameToken (stx : Syntax) (value : Name) : Bool :=
  syntaxContainsIdent stx value || syntaxContainsAtom stx value.toString

/-- Return the leftmost identifier or parser keyword in a syntax tree. -/
partial def firstNameToken? (stx : Syntax) : Option Name :=
  match stx with
  | .ident _ _ name _ => some name.eraseMacroScopes
  | .atom _ atom => some atom.toName
  | .node _ _ args => args.findSome? firstNameToken?
  | _ => none

/-- Return the leftmost atom in a syntax tree. -/
partial def firstAtom? (stx : Syntax) : Option String :=
  match stx with
  | .atom _ atom => some atom
  | .node _ _ args => args.findSome? firstAtom?
  | _ => none

/-- True when the source syntax starts with the given token. -/
def startsWithAtom (stx : Syntax) (value : String) : Bool :=
  firstAtom? stx == some value

/-- The parsed parts of a `set_option` command, term, or tactic. -/
structure SetOptionSyntax where
  optionName : Name
  value : Syntax
  stx : Syntax

/-- Parse a `set_option` syntax node, including a command wrapped in `... in`. -/
partial def setOptionSyntax? (stx : Syntax) : Option SetOptionSyntax :=
  if (stx.isOfKind ``Lean.Parser.Command.set_option ||
      stx.isOfKind ``Lean.Parser.Term.set_option ||
      stx.isOfKind ``Lean.Parser.Tactic.set_option) &&
      stx.getNumArgs > 3 && stx[1].isIdent then
    some {
      optionName := stx[1].getId.eraseMacroScopes
      value := stx[3]
      stx
    }
  else if stx.isOfKind ``Lean.Parser.Command.in && stx.getNumArgs > 0 then
    setOptionSyntax? stx[0]
  else
    none

/-- Classify a configured option as technical debt, if it is a supported marker. -/
def setOptionKind? (option : SetOptionSyntax) : Option Kind :=
  let name := option.optionName
  let isFalse := syntaxContainsNameToken option.value `false
  if name == `maxHeartbeats || name == `synthInstance.maxHeartbeats then
    some .maxHeartbeats
  else if name == `maxRecDepth then
    some .maxRecDepth
  else if name.getRoot == `backward then
    some .backwardOption
  else if name == `linter.flexible && isFalse then
    some .linterFlexible
  else if name == `linter.overlappingInstances && isFalse then
    some .linterOverlappingInstances
  else if name == `linter.auxLemma && isFalse then
    some .linterAuxLemma
  else if name == `linter.deprecated && isFalse then
    some .linterDeprecated
  else if name == `warning.simp.varHead && isFalse then
    some .simpVarHead
  else if name.getRoot == `debug || name.getRoot == `pp ||
      name.getRoot == `profiler || name.getRoot == `trace then
    if isFalse then none else some .developmentOption
  else if name == `linter.style.longFile then
    some .longFile
  else
    none

/-- True when an attribute has the given name and contains the given argument. -/
partial def hasAttributeWithArgument (stx : Syntax) (attrName argument : Name) : Bool :=
  if stx.isOfKind ``Lean.Parser.Term.attrInstance && stx.getNumArgs > 1 then
    firstNameToken? stx[1] == some attrName && syntaxContainsNameToken stx[1] argument
  else
    stx.getArgs.any (hasAttributeWithArgument · attrName argument)

/-- True when an attribute instance contains the given attribute identifier. -/
partial def hasAttribute (stx : Syntax) (attrName : Name) : Bool :=
  if stx.isOfKind ``Lean.Parser.Term.attrInstance && stx.getNumArgs > 1 then
    firstNameToken? stx[1] == some attrName
  else
    stx.getArgs.any (hasAttribute · attrName)

/-- Return the bounded command subtree that may contain command-level attributes. -/
def commandAttributes? (stx : Syntax) : Option Syntax :=
  if stx.isOfKind ``Lean.Parser.Command.declaration && stx.getNumArgs > 0 then
    some stx[0]
  else if stx.isOfKind ``Lean.Parser.Command.attribute then
    some stx
  else
    none

/-- True when a declaration command directly introduces the given parser kind. -/
def isDeclarationKind (stx : Syntax) (kind : SyntaxNodeKind) : Bool :=
  stx.isOfKind kind ||
    (stx.isOfKind ``Lean.Parser.Command.declaration && stx.getArgs.any (·.isOfKind kind))

/-- True for an `@[expose] public section`, based on the dedicated section-header slots. -/
def isExposedPublicSection (stx : Syntax) : Bool :=
  if stx.isOfKind ``Lean.Parser.Command.section && stx.getNumArgs > 0 then
    let header := stx[0]
    header.isOfKind ``Lean.Parser.Command.sectionHeader && header.getNumArgs > 1 &&
      !header[0].isNone && !header[1].isNone
  else
    false

/-- True when an `openDecl` opens a namespace, without considering selector identifiers. -/
def openDeclContainsNamespace (stx : Syntax) (namespaceName : Name) : Bool :=
  if stx.isOfKind ``Lean.Parser.Command.openHiding ||
      stx.isOfKind ``Lean.Parser.Command.openRenaming ||
      stx.isOfKind ``Lean.Parser.Command.openOnly then
    stx.getNumArgs > 0 && stx[0].isIdent &&
      stx[0].getId.eraseMacroScopes == namespaceName
  else if stx.isOfKind ``Lean.Parser.Command.openSimple then
    stx.getNumArgs > 0 && syntaxContainsIdent stx[0] namespaceName
  else if stx.isOfKind ``Lean.Parser.Command.openScoped then
    stx.getNumArgs > 1 && syntaxContainsIdent stx[1] namespaceName
  else
    false

/-- True when an `open` command opens the given namespace. -/
def openCommandContainsNamespace (stx : Syntax) (namespaceName : Name) : Bool :=
  stx.isOfKind ``Lean.Parser.Command.open && stx.getNumArgs > 1 &&
    openDeclContainsNamespace stx[1] namespaceName

/-- True when a `simp`/`dsimp` syntax enables the `instances` configuration. -/
partial def enablesInstances (stx : Syntax) : Bool :=
  if stx.isOfKind ``Lean.Parser.Tactic.posConfigItem then
    syntaxContainsIdent stx `instances
  else
    stx.getArgs.any enablesInstances

/-- Return the syntax introducing a command-level option, if present. -/
def commandSetOption? (stx : Syntax) : Option (Kind × Syntax) := do
  let option ← setOptionSyntax? stx
  let kind ← setOptionKind? option
  return (kind, option.stx)

/-- Kinds of the core `erw` surface syntax: the tactic and `conv` forms. -/
def coreErwKinds : Array SyntaxNodeKind :=
  #[``Lean.Parser.Tactic.tacticErw___, ``Lean.Parser.Tactic.Conv.convErw__]

/-- True for a source syntax node generated by one of Core Lean's `erw` parsers. -/
def isCoreErwSyntax (stx : Syntax) : Bool :=
  coreErwKinds.any stx.isOfKind &&
    match (stx.getArgs[0]? : Option Syntax) with
    | some (Syntax.atom _ "erw") => true
    | _ => false

/-- Collect supported markers represented by a command info node. -/
def commandMarkers (stx : Syntax) : Array (Kind × Syntax) := Id.run do
  let mut markers := #[]
  if let some marker := commandSetOption? stx then
    markers := markers.push marker
  let head := if stx.isOfKind ``Lean.Parser.Command.in && stx.getNumArgs > 0 then stx[0] else stx
  if head.isOfKind ``Lean.Parser.Command.unlock_limits then
    markers := markers.push (.unlockLimits, head)
  if startsWithAtom head "#adaptation_note" then
    markers := markers.push (.adaptationNote, head)
  if isExposedPublicSection head then
    markers := markers.push (.exposePublic, head)
  if openCommandContainsNamespace head `Fin.CommRing then
    markers := markers.push (.finCommRing, head)
  if openCommandContainsNamespace head `Fin.NatCast then
    markers := markers.push (.finNatCast, head)
  if isDeclarationKind head ``Lean.Parser.Command.axiom then
    markers := markers.push (.axiom, head)
  let commandAttributes? := commandAttributes? head
  if head.isOfKind ``Lean.Parser.Command.deprecated_module ||
      commandAttributes?.any (hasAttribute · `deprecated) then
    markers := markers.push (.deprecated, head)
  if commandAttributes?.any (hasAttributeWithArgument · `nolint `simpNF) then
    markers := markers.push (.simpNF, head)
  return markers

/-- Collect supported markers represented by a tactic info node. -/
def tacticMarkers (stx : Syntax) : Array (Kind × Syntax) := Id.run do
  let mut markers := #[]
  if let some option := setOptionSyntax? stx then
    if let some kind := setOptionKind? option then
      markers := markers.push (kind, option.stx)
  if isCoreErwSyntax stx then
    markers := markers.push (.erw, stx)
  if stx.isOfKind ``Lean.Parser.Tactic.simp && enablesInstances stx then
    markers := markers.push (.simpInstances, stx)
  if stx.isOfKind ``Lean.Parser.Tactic.dsimp && enablesInstances stx then
    markers := markers.push (.dsimpInstances, stx)
  if startsWithAtom stx "#adaptation_note" then
    markers := markers.push (.adaptationNote, stx)
  if startsWithAtom stx "sorry" || startsWithAtom stx "admit" then
    markers := markers.push (.sorry, stx)
  return markers

/-- Collect supported markers represented by a term info node. -/
def termMarkers (stx : Syntax) : Array (Kind × Syntax) := Id.run do
  let mut markers := #[]
  if let some option := setOptionSyntax? stx then
    if let some kind := setOptionKind? option then
      markers := markers.push (kind, option.stx)
  if stx.isOfKind ``Lean.Parser.Term.sorry then
    markers := markers.push (.sorry, stx)
  if startsWithAtom stx "#adaptation_note" then
    markers := markers.push (.adaptationNote, stx)
  return markers

/-- Build a finding from syntax that has a canonical source range. -/
def findingOfSyntax? (moduleName : Name) (file : String) (fileMap : FileMap)
    (kind : Kind) (stx : Syntax) : Option Finding := do
  let range ← stx.getRange? (canonicalOnly := true)
  let start := fileMap.toPosition range.start
  let stop := fileMap.toPosition range.stop
  return {
    moduleName
    file
    kind
    start := { start with column := start.column + 1 }
    stop := { stop with column := stop.column + 1 }
  }

/-- Add enabled syntax markers to a finding collection. -/
def addSyntaxMarkers (moduleName : Name) (file : String) (fileMap : FileMap)
    (enabledMarkers : Array Kind) (syntaxMarkers : Array (Kind × Syntax))
    (findings : Array Finding) : Array Finding := Id.run do
  let mut findings := findings
  for (kind, stx) in syntaxMarkers do
    if enabledMarkers.contains kind then
      if let some finding := findingOfSyntax? moduleName file fileMap kind stx then
        findings := findings.push finding
  return findings

/-- Collect findings from one info tree. -/
partial def collectTree (moduleName : Name) (file : String) (fileMap : FileMap)
    (enabledMarkers : Array Kind) (tree : InfoTree) (findings : Array Finding) : Array Finding :=
  match tree with
  | .context _ tree => collectTree moduleName file fileMap enabledMarkers tree findings
  | .hole _ => findings
  | .node info children =>
      let findings :=
        match info with
        | .ofCommandInfo commandInfo =>
            addSyntaxMarkers moduleName file fileMap enabledMarkers
              (commandMarkers commandInfo.stx) findings
        | .ofTacticInfo tacticInfo =>
            addSyntaxMarkers moduleName file fileMap enabledMarkers
              (tacticMarkers tacticInfo.stx) findings
        | .ofTermInfo termInfo =>
            addSyntaxMarkers moduleName file fileMap enabledMarkers
              (termMarkers termInfo.stx) findings
        | _ => findings
      children.foldl
        (fun findings child => collectTree moduleName file fileMap enabledMarkers child findings) findings

/-- True when two findings describe the same source occurrence. -/
def Finding.sameOccurrence (a b : Finding) : Bool :=
  a.moduleName == b.moduleName && a.kind == b.kind && a.start == b.start

/-- Remove duplicate nodes introduced by nested tactic/command info while preserving source order. -/
def deduplicate (findings : Array Finding) : Array Finding := Id.run do
  let mut out := #[]
  for finding in findings do
    unless out.any (·.sameOccurrence finding) do
      out := out.push finding
  return out

/-- Sort findings within a module by source position and then category. -/
def lessWithinModule (a b : Finding) : Bool :=
  if a.start.line != b.start.line then
    a.start.line < b.start.line
  else if a.start.column != b.start.column then
    a.start.column < b.start.column
  else
    a.kind.name < b.kind.name

/-- Find enabled technical debt in one module using an already loaded Lake workspace. -/
def findModuleInWorkspace (workspace : Lake.Workspace) (moduleName : Name)
    (enabledMarkers : Array Kind) : IO (Array Finding) := do
  let path ← resolveModuleSource moduleName
  let leanOptions := moduleLeanOptions workspace moduleName
  let (fileMap, trees) ← moduleInfoTreesWithOptions moduleName path leanOptions
  let mut findings := #[]
  for tree in trees do
    findings := collectTree moduleName path.toString fileMap enabledMarkers tree findings
  return (deduplicate findings).qsort lessWithinModule

/-- Sort findings by module and source position for deterministic multi-module output. -/
def lessForOutput (a b : Finding) : Bool :=
  if a.moduleName != b.moduleName then
    toString a.moduleName < toString b.moduleName
  else
    lessWithinModule a b

/-- Find enabled technical debt in modules using an already loaded Lake workspace. -/
def findModulesInWorkspace (workspace : Lake.Workspace) (moduleNames : Array Name)
    (enabledMarkers : Array Kind) : IO (Array Finding) := do
  addProjectLeanSearchPath
  let mut findings := #[]
  for moduleName in normalizeModuleNames moduleNames do
    findings := findings ++ (← findModuleInWorkspace workspace moduleName enabledMarkers)
  return findings.qsort lessForOutput

/-- Find enabled technical debt in one module. -/
def findModule (moduleName : Name) (enabledMarkers : Array Kind) : IO (Array Finding) := do
  let workspace ← loadProjectWorkspace
  addProjectLeanSearchPath
  findModuleInWorkspace workspace moduleName enabledMarkers

/-- Find enabled technical debt in a collection of modules. -/
def findModules (moduleNames : Array Name) (enabledMarkers : Array Kind) : IO (Array Finding) := do
  let workspace ← loadProjectWorkspace
  findModulesInWorkspace workspace moduleNames enabledMarkers

/-- Find enabled technical debt in a module. -/
def find (moduleName : Name) (enabledMarkers : Array Kind) : IO (Array Finding) :=
  findModules #[moduleName] enabledMarkers

/-- Render a finding as a tab-separated row. -/
def formatFinding (finding : Finding) : String :=
  s!"{finding.file}:{finding.start.line}:{finding.start.column}\t{finding.kind.name}\t{finding.kind.description}"

/-- Render a finding as a compact JSON object. -/
def formatFindingJsonLine (finding : Finding) : String :=
  Json.compress <| Json.mkObj [
    ("module", toString finding.moduleName),
    ("file", finding.file),
    ("kind", finding.kind.name),
    ("description", finding.kind.description),
    ("range", Json.mkObj [
      ("start", Json.mkObj [("line", finding.start.line), ("column", finding.start.column)]),
      ("end", Json.mkObj [("line", finding.stop.line), ("column", finding.stop.column)])])]

/-- Run the `tech-debt` command. -/
def run (config : Config) : IO Unit := do
  let workspace ← loadProjectWorkspace
  let moduleNames ← modulesForScope workspace config.scope
  let findings ← findModulesInWorkspace workspace moduleNames config.markers
  for finding in findings do
    if config.jsonl then
      IO.println (formatFindingJsonLine finding)
    else
      IO.println (formatFinding finding)

end AFTK.TechDebt
